language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
jobs:
  include:
    - stage: "Build and test WebApi"
      script:
        - dotnet build src/WebApi
        - dotnet test test/WebApi.Test
    - stage: "Build and test Web"
      script:
        - dotnet build src/Web
        - dotnet test test/Web.Test  